name: "Deploy Pet Project"
on:
  push:
    branches: ["main"]
jobs:
  deploy-pet-project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos el pull"
      - run: echo "Correr migraciones"
      - run: echo "Generar binarios"
      - run: echo "Publicar versi√≥n"